import { Mahasiswa, Dosen, Prestasi, TracerStudy, RiwayatMBKM, AnggotaPrestasi } from '../types';

export const INITIAL_DOSEN: Dosen[] = [
  {
    nip: '197508122001121002',
    nama: 'Prof. Dr. Ir. Subroto Wardoyo, M.T.',
    kode_dosen: 'SWD',
    golongan: 'IV/c',
    pangkat: 'Guru Besar',
    jabatan: 'Profesor',
    is_dosen_wali: true,
  },
  {
    nip: '198203152008012003',
    nama: 'Dr. Maria Ulfah, S.Si., M.Si.',
    kode_dosen: 'MU',
    golongan: 'III/d',
    pangkat: 'Penata Tk. I',
    jabatan: 'Lektor Kepala',
    is_dosen_wali: true,
  },
  {
    nip: '197911042005021001',
    nama: 'Ir. Hendra Wijaya, Ph.D.',
    kode_dosen: 'HW',
    golongan: 'III/c',
    pangkat: 'Penata',
    jabatan: 'Lektor',
    is_dosen_wali: true,
  }
];

export const INITIAL_MAHASISWA: Mahasiswa[] = [
  {
    npm: '12321001',
    nama: 'Bagus Adi Prasetyo',
    angkatan: 2021,
    jenis_kelamin: 'L',
    fakultas: 'FMIPA',
    prodi: 'Geofisika',
    status: 'Regulasi Akademik',
    nip_dosen_wali: '197508122001121002',
  },
  {
    npm: '12321015',
    nama: 'Farida Nur Azizah',
    angkatan: 2021,
    jenis_kelamin: 'P',
    fakultas: 'FMIPA',
    prodi: 'Geofisika',
    status: 'Regulasi Akademik',
    nip_dosen_wali: '198203152008012003',
  },
  {
    npm: '12320011',
    nama: 'Ilham Rizky Ramadhan',
    angkatan: 2020,
    jenis_kelamin: 'L',
    fakultas: 'FMIPA',
    prodi: 'Geofisika',
    status: 'Lulus',
    nip_dosen_wali: '197911042005021001',
    tahun_lulus: 2024,
  },
  {
    npm: '12318001',
    nama: 'Rian Hidayat',
    angkatan: 2018,
    jenis_kelamin: 'L',
    fakultas: 'FMIPA',
    prodi: 'Geofisika',
    status: 'Lulus',
    nip_dosen_wali: '197508122001121002',
    tahun_lulus: 2022,
  },
  {
    npm: '12319012',
    nama: 'Sarah Monica',
    angkatan: 2019,
    jenis_kelamin: 'P',
    fakultas: 'FMIPA',
    prodi: 'Geofisika',
    status: 'Lulus',
    nip_dosen_wali: '198203152008012003',
    tahun_lulus: 2023,
  },
  {
    npm: '12317025',
    nama: 'Denny Wijaya',
    angkatan: 2017,
    jenis_kelamin: 'L',
    fakultas: 'FMIPA',
    prodi: 'Geofisika',
    status: 'Lulus',
    nip_dosen_wali: '197911042005021001',
    tahun_lulus: 2021,
  },
  {
    npm: '12322005',
    nama: 'Aditya Pratama',
    angkatan: 2022,
    jenis_kelamin: 'L',
    fakultas: 'FMIPA',
    prodi: 'Geofisika',
    status: 'Regulasi Akademik',
    nip_dosen_wali: '197508122001121002',
  },
  {
    npm: '12322018',
    nama: 'Kartika Putri',
    angkatan: 2022,
    jenis_kelamin: 'P',
    fakultas: 'FMIPA',
    prodi: 'Geofisika',
    status: 'Regulasi Akademik',
    nip_dosen_wali: '198203152008012003',
  },
  {
    npm: '12320002',
    nama: 'Budi Santoso',
    angkatan: 2020,
    jenis_kelamin: 'L',
    fakultas: 'FMIPA',
    prodi: 'Geofisika',
    status: 'Alih Prodi',
    nip_dosen_wali: '197911042005021001',
  }
];

export const INITIAL_PRESTASI: Prestasi[] = [
  {
    id_prestasi: 'prestasi-0001',
    npm_mahasiswa: '12321001',
    nama_kompetisi: 'Geophysics Olympiad PIT HAGI 2025',
    tingkat: 'Nasional',
    juara_ke: 1,
    jenis_peserta: 'Individu',
    tahun_kegiatan: 2025,
    tempat: 'Bandung',
    dosen_pembimbing: 'Prof. Dr. Ir. Subroto Wardoyo, M.T.',
  },
  {
    id_prestasi: 'prestasi-0002',
    npm_mahasiswa: '12321015',
    nama_kompetisi: 'SEG Student Competition Tokyo',
    tingkat: 'Internasional',
    juara_ke: 1,
    jenis_peserta: 'Individu',
    tahun_kegiatan: 2025,
    tempat: 'Tokyo, Jepang',
    dosen_pembimbing: 'Dr. Maria Ulfah, S.Si., M.Si.',
  },
  {
    id_prestasi: 'prestasi-0003',
    npm_mahasiswa: '12320011',
    nama_kompetisi: 'Lomba Karya Tulis Geothermal IAGI',
    tingkat: 'Nasional',
    juara_ke: 2,
    jenis_peserta: 'Individu',
    tahun_kegiatan: 2024,
    tempat: 'Jakarta',
    dosen_pembimbing: 'Ir. Hendra Wijaya, Ph.D.',
  },
  {
    id_prestasi: 'prestasi-0004',
    npm_mahasiswa: '12322005',
    nama_kompetisi: 'Kompetisi Seismologi Regional',
    tingkat: 'Wilayah',
    juara_ke: 3,
    jenis_peserta: 'Individu',
    tahun_kegiatan: 2024,
  },
  {
    id_prestasi: 'prestasi-0005',
    npm_mahasiswa: '12322018',
    nama_kompetisi: 'Pekan Ilmiah Mahasiswa Nasional (PIMNAS)',
    tingkat: 'Nasional',
    juara_ke: 1,
    jenis_peserta: 'Kelompok',
    tahun_kegiatan: 2023,
    tempat: 'Yogyakarta',
    dosen_pembimbing: 'Dr. Maria Ulfah, S.Si., M.Si.',
  }
];

export const INITIAL_ANGGOTA_PRESTASI: AnggotaPrestasi[] = [
  {
    id_anggota: 'anggota-0001',
    id_prestasi: 'prestasi-0005',
    npm: '12322018',
    nama_lengkap: 'Kartika Putri',
    prodi: 'Geofisika',
    universitas: 'UNPAD',
    peran: 'Ketua Tim',
  },
  {
    id_anggota: 'anggota-0002',
    id_prestasi: 'prestasi-0005',
    npm: '12321001',
    nama_lengkap: 'Bagus Adi Prasetyo',
    prodi: 'Geofisika',
    universitas: 'UNPAD',
    peran: 'Anggota',
  },
  {
    id_anggota: 'anggota-0003',
    id_prestasi: 'prestasi-0005',
    npm: null,
    nama_lengkap: 'Dian Permata Sari',
    prodi: 'Teknik Geologi',
    universitas: 'ITB',
    peran: 'Anggota',
  },
  {
    id_anggota: 'anggota-0004',
    id_prestasi: 'prestasi-0005',
    npm: null,
    nama_lengkap: 'Alex Pratama',
    prodi: 'Fisika',
    universitas: 'Universitas Gadjah Mada',
    peran: 'Anggota',
  },
];

export const INITIAL_MBKM: RiwayatMBKM[] = [
  {
    id_mbkm: 'mbkm-0001',
    npm_mahasiswa: '12321001',
    tempat_instansi: 'Pertamina Geothermal Energy',
    semester: 'Genap 2025/2026',
    judul_topik_magang: 'Analisis Data Seismik untuk Eksplorasi Panas Bumi',
    dosen_pembimbing_lapangan: 'Bapak Andi Saputra (PGE)',
    nip_dosen_pembimbing_dalam: '197508122001121002',
    periode_magang: 'Jan 2025 - Jun 2025',
  },
  {
    id_mbkm: 'mbkm-0002',
    npm_mahasiswa: '12321015',
    tempat_instansi: 'BMKG Pusat',
    semester: 'Genap 2025/2026',
    judul_topik_magang: 'Sistem Peringatan Dini Tsunami',
    dosen_pembimbing_lapangan: 'Ibu Dr. Retno Palupi (BMKG)',
    nip_dosen_pembimbing_dalam: '198203152008012003',
    periode_magang: 'Feb 2025 - Jul 2025',
  },
  {
    id_mbkm: 'mbkm-0003',
    npm_mahasiswa: '12322005',
    tempat_instansi: 'Chevron Pacific Indonesia',
    semester: 'Ganjil 2024/2025',
    nip_dosen_pembimbing_dalam: null,
  }
];

export const INITIAL_ALUMNI: TracerStudy[] = [
  {
    id_tracer: 'tracer-0001',
    npm_mahasiswa: '12318001',
    tahun_lulus: 2022,
    status_lulusan: 'Bekerja',
    masa_tunggu_bulan: 3,
    instansi_pekerjaan: 'Pertamina Geothermal Energy',
    jabatan: 'Geophysicist',
    tingkat_perusahaan: 'Multinasional',
  },
  {
    id_tracer: 'tracer-0002',
    npm_mahasiswa: '12319012',
    tahun_lulus: 2023,
    status_lulusan: 'Bekerja',
    masa_tunggu_bulan: 8,
    instansi_pekerjaan: 'BMKG Pusat',
    jabatan: 'Seismolog Pratama',
    tingkat_perusahaan: 'Nasional',
  },
  {
    id_tracer: 'tracer-0003',
    npm_mahasiswa: '12317025',
    tahun_lulus: 2021,
    status_lulusan: 'Studi Lanjut',
    masa_tunggu_bulan: 2,
    universitas_tujuan: 'Kyushu University',
    program_studi: 'Earth Resources Engineering',
  },
  {
    id_tracer: 'tracer-0004',
    npm_mahasiswa: '12320011',
    tahun_lulus: 2024,
    status_lulusan: 'Bekerja',
    masa_tunggu_bulan: 4,
    instansi_pekerjaan: 'PT Geoservices',
    jabatan: 'Junior Geophysicist',
    tingkat_perusahaan: 'Nasional',
  },
  {
    id_tracer: 'tracer-0005',
    npm_mahasiswa: '12321001',
    tahun_lulus: 2025,
    status_lulusan: 'Wiraswasta',
    masa_tunggu_bulan: 5,
    bidang_usaha: 'Jasa Konsultasi Geofisika Tambang',
  },
  {
    id_tracer: 'tracer-0006',
    npm_mahasiswa: '12321015',
    tahun_lulus: 2025,
    status_lulusan: 'Belum Bekerja',
    masa_tunggu_bulan: 2,
  },
  {
    id_tracer: 'tracer-0007',
    npm_mahasiswa: '12322005',
    tahun_lulus: 2026,
    status_lulusan: 'Studi Lanjut',
    masa_tunggu_bulan: 0,
    universitas_tujuan: 'Institut Teknologi Bandung',
    program_studi: 'Magister Teknik Geofisika',
  },
];

